### PR TITLE
support mysql

### PR DESCRIPTION
**Pull request by josephholsten**
also some minor improvements:

- default to `pg` engine
- use supermarket source
- support single or multiple actions

### CODE REVIEW

**Comment by mmzyk** [comment]
Thanks @josephholsten. The main maintainer of this is on vacation at the moment, but I'll be sure he sees it once he's back in the office.

**Comment by tas50** [comment]
@josephholsten Any chance you can rebase this PR?

**Comment by iennae** [comment]
@josephholsten Apologies for the delay in responding to your request. Thanks for your contributions here. I've gone ahead and rebased your contributions at PR #6.

**Comment by josephholsten** [comment]
awesome, thanks!

**Pull request closed without merging**
